name: Build and Push Docker Images (Separate Arch)

on:
  push:
    tags:
      - '*'  # Run on any new tag
  workflow_dispatch:

jobs:
  build-and-push-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push amd64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            luismachadoreis/postgres-multidb-pgvector:pg17-${{ steps.vars.outputs.short_sha }}
            luismachadoreis/postgres-multidb-pgvector:pg17
            luismachadoreis/postgres-multidb-pgvector:pg17-amd64
            luismachadoreis/postgres-multidb-pgvector:latest
            luismachadoreis/postgres-multidb-pgvector:latest-amd64

  build-and-push-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push arm64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            luismachadoreis/postgres-multidb-pgvector:pg17-${{ steps.vars.outputs.short_sha }}-arm64
            luismachadoreis/postgres-multidb-pgvector:pg17-arm64
            luismachadoreis/postgres-multidb-pgvector:pg17-arm64-${{ steps.vars.outputs.short_sha }}
            luismachadoreis/postgres-multidb-pgvector:latest-arm64
